// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9rCABwzPmU-cvyPNA3dEIjERFfsy4Y0',
    appId: '1:171151443059:web:2ddbcddf48adc0f97c1606',
    messagingSenderId: '171151443059',
    projectId: 'aplikasi-scan-plat-nomor',
    authDomain: 'aplikasi-scan-plat-nomor.firebaseapp.com',
    storageBucket: 'aplikasi-scan-plat-nomor.appspot.com',
    measurementId: 'G-4HNMTBEGZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmQvfPvy8sXMRKx46qX_wNgl3udgY98U',
    appId: '1:171151443059:android:22f8d61b991ea41c7c1606',
    messagingSenderId: '171151443059',
    projectId: 'aplikasi-scan-plat-nomor',
    storageBucket: 'aplikasi-scan-plat-nomor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE67ZlR1djJXMGe_UiBit2rAeARFBiqcg',
    appId: '1:171151443059:ios:9ce61e84e98ffd747c1606',
    messagingSenderId: '171151443059',
    projectId: 'aplikasi-scan-plat-nomor',
    storageBucket: 'aplikasi-scan-plat-nomor.appspot.com',
    iosClientId: '171151443059-alfkrkbefit8nhd4tsq9d67vpvs1pk7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiScanPlatNomor',
  );
}
